# SPDX-License-Identifier: GPL-2.0

ccflags-y := -Wformat

# Samsung Debugging Features
obj-$(CONFIG_SEC_DEBUG_BASE_BUILT_IN)		+= sec_debug_base_built.o
obj-$(CONFIG_SEC_DEBUG_AUTO_COMMENT)		+= sec_debug_auto_comment_built.o
obj-$(CONFIG_SEC_DEBUG_MEMTAB)			+= sec_debug_memtab_built.o

