obj-$(CONFIG_UH_DEBUG_LOG)        += uh_debug_log.o
obj-$(CONFIG_RKP)                 += rkp.o
obj-$(CONFIG_RKP)                 += rkp_module_support.o
obj-$(CONFIG_RKP_TEST)            += rkp_test.o
obj-$(CONFIG_KDP)                 += kdp.o
obj-$(CONFIG_KDP_TEST)            += kdp_test.o
ccflags-y := -Wformat
